services:
  java-dev-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java-dev-app
    ports:
      - "8000:8000"
    platform: linux/amd64
    environment:
      - TZ=Asia/Shanghai
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xmx512m -Xms256m
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: json-file
      options:
        max-size: "100M"
        max-file: "10"
    networks:
      - java-app-network

networks:
  java-app-network:
    driver: bridge
